name: Terraform CI

on:
  pull_request:
    branches: ["master"]
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

  push:
    branches: ["master"]
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

concurrency:
  group: terraform-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    working-directory: infra

env:
  TF_VAR_FILE: envs/dev.auto.tfvars
  TF_PLAN_FILE: tfplan
  TF_VAR_pg_master_password: ${{ secrets.PG_MASTER_PASSWORD }}
  TF_VAR_airflow_admin_password: ${{ secrets.AIRFLOW_ADMIN_PASSWORD }}
  TF_VAR_airflow_api_auth_jwt_secret: ${{ secrets.AIRFLOW_API_AUTH_JWT_SECRET }}
  TF_VAR_airflow_core_fernet_key: ${{ secrets.AIRFLOW_CORE_FERNET_KEY }}
  TF_VAR_airflow_core_api_secret_key: ${{ secrets.AIRFLOW_CORE_API_SECRET_KEY }}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Format check
        run: terraform fmt -check -recursive -diff

      - name: Init
        run: terraform init -input=false

      - name: Validate
        run: terraform validate

      - name: Plan (PR)
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -input=false \
            -var-file="${{ env.TF_VAR_FILE }}" 

      - name: Plan (saved)
        if: github.event_name == 'push'
        run: |
          terraform plan -input=false \
            -var-file="${{ env.TF_VAR_FILE }}" \
            -out="${{ env.TF_PLAN_FILE }}"

      - name: Verify plan file exists
        if: github.event_name == 'push'
        run: ls -lah

      - name: Upload plan artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v6
        with:
          name: terraform-plan
          path: infra/${{ env.TF_PLAN_FILE }}
          if-no-files-found: error
          retention-days: 7

      - name: Debug plan file
        if: github.event_name == 'push'
        run: |
          pwd
          ls -lah

  apply:
    name: Terraform Apply 
    runs-on: ubuntu-latest
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Init
        run: terraform init -input=false

      - name: Download plan artifact
        uses: actions/download-artifact@v6
        with:
          name: terraform-plan
          path: infra

      - name: Apply saved plan
        run: terraform apply -auto-approve "${{ env.TF_PLAN_FILE }}"